apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: web
          image: httpd
